### ISSUE TITLE
data.js feedback

### ISSUE THREAD

**Issue by miwst** [SpenGietz/301-portfolio-assignment#8]
Code functionality is really impressive.  I like the sliding project pagination.  The overall data structure can be more organized.  Can consolidate into one constructor and remove the others.  Some of the longer conditionals can be refactored into functions.  $.delay() method can be implemented to replace all instances of setTimeout().  This code could really benefit from a more functional approach to handle all the animations under different page count conditions.  Functionality is there, code could just be more concise and readable.

**Comment by SpenGietz** [comment]
We got a ton of lines of code in my functions in JavaScript and I am going further with a way to fix the direction problem. We got the data structures set up so I can change that exactly and have much less code than before hand.
